# LECTURE 1.1 - Introduction to Numerical Computing Using Numpy

***
## Table of Contents
* [Part 1](#part1)
    * [Initialize y_hat and y](#initialize)
    * [Creating Loss Value (L) Functions](#lossvalue)
        Implementing the regression loss functions
        * [Mean Squared Error (MSE)](#mse)
        * [Mean Absolute Error (MAE)](#mae)
        * [Mean Squared Logarithmic Error (MSLE)](#msle)
        * [Mean Absolute Percentage Error (MAPE)](#mape)
        
* [Part 2](#part2)
    * [Creating 1D array using *arange* function](#arange)
    * [Reshaping M into 4x4 array](#arrn)
    * [Getting the 2nd row of N](#2ndrow)
    * [Getting the minimum value for each column of N](#minval)
    * [Getting the locations of the minimum values for each column of N](#minloc)
    * [Getting the average of the N matrix](#avgn)
    * [Creating vector V with 4 elements, each element is 1](#vectorv)
    * [Dot product of N and V](#dotproduct)

## Part 1 <a class="anchor" id="part1"></a>
***

### Import the *numpy* library

In [1]:
import numpy as np

### Initliazing *y_hat* and *y* with 20 linearly spaced numbers between -1 and 1, and 0 and 1, respectively <a class="anchor" id="initialize"></a>

For this one we will use the `linspace()` function. We will also create the `1-D` arrays of both *y* and *y_hat* to be used later on the succeeding parts.

In [2]:
num = 20

# 20 linspace between 0 and 1
y = np.linspace(0, 1, num)

# 20 linspace between -1 and 1
y_hat = np.linspace(-1, 1, num)

### Computing for the *shape* and *dimension* of y_hat and y

In [3]:
# Shape
print(y_hat.shape)
print(y.shape)

# Dimension
print(y_hat.dtype)
print(y.dtype)

(20,)
(20,)
float64
float64


# Creating Loss Value (L) Functions <a class="anchor" id="lossvalue"></a>

Each of the functions will return the loss value **L** with *y* and *y_hat* as parameters

### Mean Squared Error (MSE) <a class="anchor" id="mse"></a>

In [4]:
# MSE function
def meanSqrdErr(arr1, arr2):
    loss = np.mean(np.square(arr1 - arr2))
    return loss

In [5]:
meanSqrdErr(y, y_hat)

0.3421052631578948

### Mean Absolute Error (MAE) <a class="anchor" id="mae"></a>

In [6]:
# MAE function
def meanAbsErr(arr1, arr2):
    loss = np.mean(np.abs(arr1 - arr2))
    return loss

In [7]:
meanAbsErr(y, y_hat)

0.4999999999999999

### Mean Squared Logarithmic Error (MSLE) <a class="anchor" id="msle"></a>

For MSLE, there is an occuring RuntimeWarning: divide by zero encountered with `inf` as the output. My workaround to this fix is to assign the -1 value of *y_hat* instead to -0.99 so that it will not be mathematically be zero when dividing.

In [8]:
# MSLE function
def meanSqrdLogErr(arr1, arr2):
    arr2[0] = -0.99
    loss = np.mean(np.square(np.log1p(arr1) - np.log1p(arr2)))
    return loss

In [9]:
meanSqrdLogErr(y, y_hat)

1.7308773009244085

### Mean Absolute Percentage Error (MAPE) <a class="anchor" id="mape"></a>

Same with MSLE, MAPE is also encountering a RuntimeWarning in which a zero is encountered in true divide. A leeway for this fix is to assign the first index of *y* value to 0.01 as it is the nearest to 0.

In [10]:
# MAPE function
def meanAbsPrcntErr(arr1, arr2):
    arr1[0] = 0.01
    loss = np.mean(np.abs((arr1 - arr2) / arr1) * 0.100)
    return loss

In [11]:
meanAbsPrcntErr(y, y_hat)

0.7420352674286499


## Part 2 <a class="anchor" id="part2"></a>
***

### Creating 1D array using *arange* function <a class="anchor" id="arange"></a>

In [12]:
M = np.arange(1, 17)

### Reshaping M into 4x4 array and store it into N <a class="anchor" id="arrn"></a>

In [13]:
N = np.reshape(M, (4,4))
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Getting the 2nd row of N <a class="anchor" id="2ndrow"></a>

In [14]:
secondRow = N[1]
secondRow

array([5, 6, 7, 8])

### Getting the minimum value for each column of N <a class="anchor" id="minval"></a>

In [15]:
minVal = np.min(N, axis=0)
minVal

array([1, 2, 3, 4])

### Getting the locations of the minimum values for each column of N <a class="anchor" id="minloc"></a>

In [16]:
minLoc = np.argmin(N, axis=0)
minLoc

array([0, 0, 0, 0])

### Getting the average of the N matrix <a class="anchor" id="avgn"></a>

In [17]:
avgN = np.mean(N)
avgN

8.5

### Creating vector V with 4 elements, each element is 1 <a class="anchor" id="vectorv"></a>

In [18]:
V = np.ones(4, dtype='int32')
V

array([1, 1, 1, 1], dtype=int32)

### Dot product of N and V <a class="anchor" id="dotproduct"></a>

In [19]:
dotProduct = np.dot(N, V)
dotProduct

array([10, 26, 42, 58])